trigger:
  branches:
    include:
      - master
  paths:
    include:
      - app/*

variables:
  - group: terraform-backend

stages:
  - template: './pipeline-templates/deploy-module.yml'
    parameters:
      name: 'Test Core'
      backend_key: 'test.core.tfstate'
      directory: 'core'
      variables_file: 'test.tfvars'

  - template: './pipeline-templates/deploy-module.yml'
    parameters:
      name: 'Test Data'
      backend_key: 'test.data.tfstate'
      directory: 'data'
      variables_file: 'test.tfvars'

  - template: './pipeline-templates/deploy-module.yml'
    parameters:
      name: 'Test App'
      backend_key: 'test.app.tfstate'
      directory: 'app'
      variables_file: 'test.tfvars'
