trigger:
  branches:
    include:
      - master
  paths:
    include:
      - app/*

variables:
  - group: terraform-backend

stages:
  - template: './pipeline-templates/deploy-module.yml'
    parameters:
      name: 'Dev Core'
      backend_key: 'dev.core.tfstate'
      directory: 'core'
      variables_file: 'dev.tfvars'

  - template: './pipeline-templates/deploy-module.yml'
    parameters:
      name: 'Dev Data'
      backend_key: 'dev.data.tfstate'
      directory: 'data'
      variables_file: 'dev.tfvars'

  - template: './pipeline-templates/deploy-module.yml'
    parameters:
      name: 'Dev App'
      backend_key: 'dev.app.tfstate'
      directory: 'app'
      variables_file: 'dev.tfvars'
