trigger:
  branches:
    include:
      - master
  paths:
    include:
      - app/*

variables:
  - group: terraform-backend

stages:
  - template: './pipeline-templates/deploy-module.yml'
    parameters:
      name: 'Test'
      backend_key: 'test.tfstate'
      directory: 'app'
      variables_file: 'test.tfvars'
