trigger: none

variables:
  - group: terraform-backend

stages:
  - template: './pipeline-templates/deploy-module.yml'
    parameters:
      name: 'Production'
      backend_key: 'production.terraform.tfstate'
      directory: 'app'
      variables_file: 'production.tfvars'
